version: "3"
services:
  mongo:
    image: mongo
    volumes: 
      - /home/andrelsa/Documentos/estudoDocker/NJSLearn/mongo:/data/db
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: demolabbs
    networks:
      net-frontend:
    #    ipv4_address: 172.19.0.10

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: demolabbs
    networks: 
      # et-backend:
      net-frontend:
        # ipv4_address: 172.21.0.1

  node-web-app:
    image: andreaguiarbr/node-web-app:latest
    depends_on: 
      - mongo
    volumes:
      - /home/andrelsa/Documentos/estudoDocker/NJSLearn/node_modules:/app
      - /home/andrelsa/Documentos/estudoDocker/NJSLearn/node_modules/logs:/root/.npm/_logs
    networks: 
      # net-backend:
      net-frontend:
        ipv4_address: 172.20.0.10


networks:
  net-backend:
    driver: bridge
    # ipam:
    #   config:
    #   - subnet: 172.19.0.0/24   
  net-frontend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24 