version: "3"
services:
  mongo:
    image: mongo
    volumes: 
      - /home/f0739445/Documentos/labbs/nodejs/mongo:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demolabbs
    networks:
      - net-backend

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on: 
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: demolabbs
  #   networks: 
  #     - net-backend
  #     - net-frontend

  node-web-app:
    image: andrelsa/node-web-app:latest 
    ports:
      - 8080:8080
    depends_on: 
      - mongo
    networks: 
      - net-backend
      - net-frontend

  prometheus:
    image: prom/prometheus
    volumes:
      - /home/f0739445/Documentos/labbs/nodejs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - net-frontend

networks:
  net-backend:
    driver: bridge
  net-frontend:
    driver: bridge