version: "3"
services:
  mongo:
    image: mongo
    volumes: 
      - /home/f0739445/Documentos/labbs/nodejs/mongo:/data/db
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
    #   MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PWD
    networks:
      - net-backend

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on: 
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USER
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PWD
  #   networks: 
  #     - net-backend
  #     - net-frontend

  node-web-app:
    image: andrelsa/node-web-app:latest 
    ports:
      - 8080:8080
    depends_on: 
      - mongo
    env_file: .env
    # environment:
    #   MONGO_ROOT_USER: $MONGO_ROOT_USER
    #   MONGO_ROOT_PWD: $MONGO_ROOT_PWD
    networks: 
      - net-backend
      - net-frontend

  prometheus:
    image: prom/prometheus
    volumes:
      - /home/f0739445/Documentos/labbs/nodejs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - net-frontend

  grafana:
    image: grafana/grafana:5.3.2
    volumes:
      - vol-grafana:/var/lib/grafana
    # user: "472"
    ports:
      - 3000:3000
    networks: 
      - net-frontend

networks:
  net-backend:
    driver: bridge
  net-frontend:
    driver: bridge

volumes:
  vol-grafana: