version: "3"
services:
  mongo:
    image: mongo
    volumes: 
      - /mnt/dados/andrelsa/meunode/mongo:/data/db
    ports:
      - "27017"
    env_file: 
      - mongo.env
    networks:
      - net-backend

  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - "8081"
    env_file: 
      - mongoexp.env
    networks: 
      - net-backend
      - traefik-net

  node-web-app:
    image: registry.labbs.com.br/andrelsa/meunode:0.0.1-SNAPSHOT 
    ports:
      - "8080"
    depends_on: 
      - mongo
    env_file: 
      - .env
    environment: 
      - MONGO_ROOT_USER=root
      - MONGO_ROOT_PWD=demolabbs
    networks: 
      - net-backend
      - traefik-net

  prometheus:
    image: registry.labbs.com.br/andrelsa/prometheus:0.0.1-SNAPSHOT
    ports:
      - "9090"
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=mynodeapp@andrelsa-meunode_node-web-app:8080/metrics
    networks: 
      - traefik-net

  grafana:
    image: registry.labbs.com.br/andrelsa/grafana:0.0.1-SNAPSHOT
    ports:
      - "3000"
    networks: 
      - traefik-net

  nginxproxy:
    image: registry.labbs.com.br/andrelsa/nginx-proxy:0.0.1-SNAPSHOT
    environment: 
      - PROXY_DESTINATION_1=80|/|http|andrelsa-meunode_node-web-app|8080
      - PROXY_DESTINATION_2=3000|/|http|andrelsa-meunode_grafana|3000
      - PROXY_DESTINATION_3=9090|/|http|andrelsa-meunode_prometheus|9090
      - PROXY_DESTINATION_4=8081|/|http|andrelsa-meunode_mongo-express|8081

    depends_on:
      - prometheus
      - node-web-app
      - grafana
    ports:
      - "3000:3000"
      - "9090:9090"
      - "8081:8081"
    networks: 
      - traefik-net
    deploy:
      labels:
         - traefik.docker.network=traefik-net
         - traefik.frontend.rule=Host:andrelsa-app1.labbs.com.br
         - traefik.port=80
         - traefik.frontend.entryPoints=internal_http,internal_https,external_http,external_https


networks:
  net-backend:
    driver: overlay
  traefik-net:
    external:
      name: traefik-net 


# volumes:
#   vol-nodegrafana:
#   vol-mongobase: 