version: "3"
services:
  mongo:
    image: mongo
    volumes: 
      - /home/f0739445/Documentos/labbs/nodejs/mongo:/data/db
    restart: always
    ports:
      - "27017"
    env_file: 
    - mongo.env
    networks:
      - net-backend

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - "8081"
    env_file: 
      - mongoexp.env
    networks: 
      - net-backend
      - net-frontend

  node-web-app:
    image: andrelsa/node-web-app:latest 
    ports:
      - "8080"
    depends_on: 
      - mongo
    env_file: .env
    networks: 
      - net-backend
      - net-frontend

  prometheus:
    image: prom/prometheus
    volumes:
      - /home/f0739445/Documentos/labbs/nodejs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090"
    networks:
      - net-frontend

  grafana:
    image: grafana/grafana:5.3.2
    volumes:
      - vol-grafana:/var/lib/grafana
    ports:
      - "3000"
    networks: 
      - net-frontend

  nginxproxy:
    image: nginx
    volumes:
     - /home/f0739445/Documentos/labbs/nodejs/nginx/:/etc/nginx/
    depends_on:
      - prometheus
      - node-web-app
      - grafana
    ports:
      - "80:80"
      - "3000:3000"
      - "9090:9090"
      - "8081:8081"
    networks: 
      - net-frontend

networks:
  net-backend:
    driver: bridge
  net-frontend:
    driver: bridge

volumes:
  vol-grafana: