{
 "title": "My node app",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Invocações",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mynodeapp_qt_invocacao{endpoint!='/metrics'})",
     "legendFormat": "Total de Invocações"
    }
   ]
  },
  {
   "title": "Container Up Time",
   "type": "singlestat",
   "description": "Tempo de vida do container",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    { "expr": "mynodeapp_uptime_seconds" }
   ]
  },
  {
   "title": "Invocações por Endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Chamadas" }
   ],
   "targets": [
    {
     "expr": "mynodeapp_qt_invocacao{endpoint!='/metrics'}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}